# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e5b052ab62b08b13ccd85fd24de30333669b9106ca877dd2f0790fd8659a54bf81e09247dfe4135315ab8d576267919df8a9ceed9ff92bab3288b34b5a9b400

test:
  secret_key_base: 9ac3f607067dc5fc11dcf53c9e12b5a404dce4f524ebafbf886fe9a84aac7655003f59ec95d4af4098f9b3f255c2a2b0aacf2dfad56f82cdfff59b1d952bb8da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
